on: push
name: ğŸ› ï¸ Build and ğŸ©º Test Application on push
jobs:
  webClient:
    name: ğŸ–¥ï¸ WebClient
    runs-on: ubuntu-latest
    steps:
    - name: ğŸšš Get latest code
      uses: actions/checkout@v3

    - name: ğŸŸ¢ Use Node.js 18.16.0
      uses: actions/setup-node@v2
      with:
        node-version: '18.16.0'
      
    - name: ğŸ› ï¸ Build WebClient
      run: |
        cd WebClient
        npm install
        npm run build
    
    - name: ğŸ—‚ï¸ List output files
      run: |
        echo "ğŸš¨ Build files: "
        cd WebClient
        find dist/
  API:
    name: ğŸŒ API
    runs-on: ubuntu-latest
    steps:
      - name: ğŸšš Get latest code
        uses: actions/checkout@v3

      - name: ğŸ“¦ Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: ğŸ› ï¸ Build and ğŸ©º Test API
        run: |
          cd API/BlueFlagGreekBeaches/
          mvn --batch-mode --update-snapshots verify